### ISSUE TITLE
Lambda Expressions not Supported

### ISSUE THREAD

**Issue by samseen** [exp0nge/UniversityInformationManagementSystem_FinalProject#1]
IntelliJ IDEA complains that some classes have Lambda Expressions that are not supported at this language level. How do I resolve this?

**Comment by exp0nge** [comment]
You need to change your Java to version 8 to allow lambdas. I believe you can do this is File>project structure

**Comment by samseen** [comment]
Thank you, I've resolved it. Why is it not getting past the Login interface? I just get this Password/Username error even though I registered or use the admin credentials.

**Comment by exp0nge** [comment]
If you are in the Faculty UI, then you need to use a privileged account (username: admin, password: pass). Also, try to use the JAR file in artifacts.

**Comment by samseen** [comment]
I think it's complaining of the path not been accessible... dbAdmin.CSV.... it's throwing a FileNotFoundException. I'm still trying to tweak it.

**Comment by exp0nge** [comment]
I will have to check what's wrong later in the night.

**Comment by exp0nge** [comment]
Okay, I updated the files, you should be able to login now. You can also just run the JAR file in the artifacts folder.

**Comment by samseen** [comment]
It works now. I appreciate your support.
